// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
export {}
